--=======GPP=======--
INSERT INTO Building_GreatPersonPoints(BuildingType, GreatPersonClassType, PointsPerTurn) VALUES('BUILDING_OP_BUILDING', 'GREAT_PERSON_CLASS_PROPHET', 3);

--=======Modifiers=======--
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES('OP_BUILDING_RELIGION_PRESSURE', 'MODIFIER_SINGLE_CITY_RELIGION_PRESSURE');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES('OP_BUILDING_RELIGION_EXTRA_PROMOTION', 'MODIFIER_SINGLE_CITY_RELIGION_EXTRA_PROMOTIONS');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES('OP_BUILDING_RELIGION_UNLIMITED_PROMOTION', 'MODIFIER_PLAYER_UNIT_GRANT_UNLIMITED_PROMOTION_CHOICES');

--=======Modifiers Arguments=======--
INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES('OP_BUILDING_RELIGION_PRESSURE', 'Amount', 'ARGTYPE_IDENTITY', '500');
INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES('OP_BUILDING_RELIGION_EXTRA_PROMOTION', 'Amount', 'ARGTYPE_IDENTITY', '2');
INSERT INTO ModifierArguments(ModifierId, Name, Type, Value) VALUES('OP_BUILDING_RELIGION_UNLIMITED_PROMOTION', 'UnitType', 'ARGTYPE_IDENTITY', 'UNIT_APOSTLE');

--=======Building Modifiers=======--
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES('BUILDING_OP_BUILDING', 'OP_BUILDING_RELIGION_PRESSURE');
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES('BUILDING_OP_BUILDING', 'OP_BUILDING_RELIGION_EXTRA_PROMOTION');
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES('BUILDING_OP_BUILDING', 'OP_BUILDING_RELIGION_UNLIMITED_PROMOTION');